name: "Release CLI"

on:
  workflow_dispatch:
    inputs:
      release_tag:
        type: string
        required: true
        description: "The release tag to create. E.g. `aptos-cli-v0.2.3`:"
      branch:
        type: string
        required: true
        description: ""

jobs:
  build-linux-binary:
    name: "Build Linux binary"
    runs-on: "ubuntu-latest"
    steps:
      - name: Pull aptos
        uses: actions/checkout@v3
        with: 
          repository: 'aptos-labs/aptos-core'
          ref: ${{ github.event.inputs.branch }}
      - name: Pull aptos-cli-build
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
          path: builder
      - name: Build CLI
        run: ./builder/build.sh
      - name: Upload Binary
        uses: actions/upload-artifact@v3
        with:
          name: cli-builds
          path: aptos-cli-*.zip

  build-os-x-binary:
    name: "Build OS X binary"
    runs-on: macos-latest
    steps:
      - name: Pull aptos
        uses: actions/checkout@v3
        with: 
          repository: 'aptos-labs/aptos-core'
          ref: ${{ github.event.inputs.branch }}
      - name: Pull aptos-cli-build
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
          path: builder
      - name: Build CLI
        run: ./builder/build.sh
      - name: Upload Binary
        uses: actions/upload-artifact@v3
        with:
          name: cli-builds
          path: aptos-cli-*.zip

  release-binaries:
    name: "Release binaries"
    needs:
      - build-linux-binary
      - build-os-x-binary
    runs-on: ubuntu-latest
    permissions:
      contents: "write"
      pull-requests: "read"
    steps:
      - name: Download prebuilt binaries
        uses: actions/download-artifact@v3
        with:
          name: cli-builds
      - name: Create GitHub Release
        uses: "marvinpinto/action-automatic-releases@v1.2.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ github.event.inputs.release_tag }}"
          prerelease: false
          title: "${{ github.event.inputs.release_tag }}"
          files: |
            aptos-cli-*.zip